"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var objcricle = new circle_1.Circle(2);
objcricle.Myarea();
objcricle.Display();
var Rect = new rectangle_1.Rectangle(2, 3);
Rect.Myarea();
Rect.Display();
